[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-portroyal_darkbg
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-portroyal_darkbg
GtkTheme=oomox-portroyal_darkbg
IconTheme=oomox-portroyal_darkbg
MetacityTheme=oomox-portroyal_darkbg
